server: 
  port: 9008
spring: 
  application:  
    name: tensquare_user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.162.160:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 39.105.162.160
  rabbitmq:
    host: 39.105.162.160